SELECT RET.ID, 
    CASE 
        WHEN RET.CHILD_COUNT IS NULL THEN 0
        ELSE RET.CHILD_COUNT
    END AS CHILD_COUNT
FROM (
    SELECT ED.ID, CHILD_COUNT
    FROM ECOLI_DATA ED LEFT OUTER JOIN (
    SELECT PARENT_ID AS ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
    HAVING PARENT_ID IS NOT NULL) STATS ON ED.ID = STATS.ID
) AS RET
ORDER BY RET.ID;