# 21년 가입 회원 중 상품을 구매한 회원수와 상품을 구매한 회원의 비율을 년, 월 별로 출력하기

# 21년 구매 건 수 출력하기

SELECT 
    YEAR(ONLINE_SALE.SALES_DATE) AS YEAR,
    MONTH(ONLINE_SALE.SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_INFO.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT USER_INFO.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1
    ) AS PURCHASED_RATIO
FROM
    USER_INFO 
    JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
WHERE 
    USER_INFO.JOINED LIKE '2021%'
GROUP BY 
    YEAR, MONTH
ORDER BY 
    YEAR, MONTH;
