SELECT CHILD.ID, CHILD.GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM 
(
    SELECT * FROM ECOLI_DATA
) AS PARENT
JOIN
(
    SELECT * FROM ECOLI_DATA
) AS CHILD
ON (CHILD.PARENT_ID = PARENT.ID AND (PARENT.GENOTYPE & CHILD.GENOTYPE) = PARENT.GENOTYPE)
ORDER BY CHILD.ID;