



# 2022.08 ~ 2022.10 까지 대여 횟수가 5회 이상인 자동차에 한해
# 2022.08 ~ 2022.10 사이의 월별 자동차 ID별 총 대여 횟수

# 2022.08 ~ 2022.10 사이 대여 횟수가 5회 이상인 자동차
# SELECT *, COUNT(*) AS COUNT
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
# GROUP BY CAR_ID
# HAVING COUNT(*) >= 5


# 2022.08 ~ 2022.10 사이 월별 대여가 모자란 자동차
# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
# GROUP BY CAR_ID, MONTH
# HAVING COUNT(*) < 3

# SELECT MONTH, CAR_ID, COUNT(*) AS RECORDS
# FROM 
#     (SELECT MONTH(OVER_FIVE.START_DATE) AS MONTH, OVER_FIVE.CAR_ID
#     FROM (
#         SELECT *, COUNT(*) AS COUNT
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#         WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
#         GROUP BY CAR_ID
#         HAVING COUNT(*) >= 5
#     ) AS OVER_FIVE JOIN
#     (
#         SELECT *
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#         WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
#         GROUP BY CAR_ID, MONTH(START_DATE)
#         HAVING COUNT(*) >= 3
#     ) AS EVERY_USE
#     ON OVER_FIVE.CAR_ID = EVERY_USE.CAR_ID) AS RET
# GROUP BY MONTH, CAR_ID
# ORDER BY MONTH, CAR_ID DESC;
    
    
    
    
WITH RentalCounts AS (
    SELECT 
        CAR_ID,
        COUNT(*) AS TOTAL_RENTALS
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
        START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
    GROUP BY 
        CAR_ID
    HAVING 
        COUNT(*) >= 5
),
FilteredRentals AS (
    SELECT 
        CAR_ID,
        MONTH(START_DATE) AS MONTH
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
        START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
        AND CAR_ID IN (SELECT CAR_ID FROM RentalCounts)
)
SELECT 
    MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM 
    FilteredRentals
GROUP BY 
    MONTH, CAR_ID
HAVING 
    COUNT(*) > 0
ORDER BY 
    MONTH ASC,
    CAR_ID DESC;
