SELECT YEAR, YEAR_DEV, ID
FROM ( 
    SELECT ED.ID, MAX_COLONY - ED.SIZE_OF_COLONY AS YEAR_DEV, MAX_ED.YEAR
    FROM ECOLI_DATA AS ED JOIN (
        SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_COLONY
        FROM ECOLI_DATA
        GROUP BY YEAR) AS MAX_ED 
        ON YEAR(ED.DIFFERENTIATION_DATE) = YEAR) AS RET
ORDER BY YEAR, YEAR_DEV;

# SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_COLONY
# FROM ECOLI_DATA
# GROUP BY YEAR