-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/", BOARD_ID, "/", FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM (
    SELECT B.BOARD_ID, F.FILE_ID, F.FILE_EXT, F.FILE_NAME
    FROM USED_GOODS_BOARD B 
    JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
    JOIN (
        SELECT BOARD_ID, RANK() OVER (ORDER BY VIEWS DESC) AS RANKING
        FROM USED_GOODS_BOARD
        LIMIT 1) AS R ON R.BOARD_ID = B.BOARD_ID
) AS RET
ORDER BY FILE_ID DESC;